defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  min_messages: warning
  timeout: 5000
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 1_000).to_i %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>

development:
  <<: *defaults
  database: development
  gssencmode: disable
  pool: 30

test:
  <<: *defaults
  database: test
  gssencmode: disable
  pool: 30

production:
  <<: *defaults
  database: <%= ENV.fetch("DB_NAME", "postgres") %>
  gssencmode: disable
  pool: 30